version: '3.7'

networks:
    app-network:
        driver: bridge

services:
    app:
        image: user_auth-${APP_ENV}-app
        container_name: user_auth_app
        build:
            context: devops/app
        environment:
            APP_DEBUG: ${APP_DEBUG}
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}?serverVersion=8&charset=utf8
        networks:
            - app-network
        ports:
            - 8080:80
        volumes:
            - .:/app

    database:
        image: 'mysql:latest'
        container_name: user_auth_mysql
        volumes:
          - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        networks:
            - app-network
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - '3306:3306'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: user_auth_phpmyadmin
        depends_on:
            - database
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network
        ports:
            - 8082:80